Private and Public routes logic
Leila-2/wallet-project pull request #12
Opened 2022-04-03 10:00 UTC by Meelenych

Добавил основную логику для публичных и приватных раутов

2022-04-04 16:26 UTC, Telekaster requested changes

2022-04-04 16:26 UTC, Telekaster commented on src/App.js
Зачем оставлять заккоментированный код?

2022-04-04 16:26 UTC, Telekaster commented on src/App.js
> +
Удалить

2022-04-04 16:26 UTC, Telekaster commented on src/App.js
>  		<>
Удалить

2022-04-04 16:58 UTC, Meelenych commented on src/App.js
>  		<>
Удалил

2022-04-04 17:51 UTC, Meelenych commented on src/App.js
> +
удалил

2022-04-04 17:52 UTC, Meelenych commented on src/App.js
удалил

2022-04-04 21:23 UTC, Telekaster approved these changes

2022-04-05 09:49 UTC, Leila-2 approved these changes

2022-04-05 10:15 UTC, Leila-2 requested changes

2022-04-05 10:15 UTC, Leila-2 commented on src/App.js
> +				<Container>
Сними контейнер пж)
в Контейнер мы оборачиваем только контент

2022-04-05 10:28 UTC, Leila-2 approved these changes

2022-04-05 10:31 UTC, merged