header/add header
Leila-2/wallet-project pull request #15
Opened 2022-04-04 14:46 UTC by moriarty15

adds a header with a logo and buttons name and exit

2022-04-04 16:46 UTC, Telekaster requested changes
Глобально переделать. Свяжись со мной по видеосвязи я тебе покажу

2022-04-04 16:46 UTC, Telekaster commented on src/App.js
> +import Header from "./components/Header/Header";
Перенеси пожалуйста компонент в pages/MainPage/components

2022-04-04 16:46 UTC, Telekaster commented on src/App.js
> +			<Header/>
Пока удали его отсюда, он будет рендерится только при определенном path, а не всегда быть на экране

2022-04-05 14:25 UTC, Telekaster approved these changes
Молодец

2022-04-05 15:55 UTC, Leila-2 reviewed
Супер!

2022-04-05 16:39 UTC, merged