header/refactoring + avatar plug
Leila-2/wallet-project pull request #25
Opened 2022-04-06 13:44 UTC by moriarty15

небольшой рефакторинг + заглушка место для аватарки

2022-04-07 10:48 UTC, Leila-2 commented on src/pages/MainPage/components/Header/Header.jsx
> +        <Link to="/" className="FlexGroops">
Класс наверное лучше писать с маленькой буквы, но это просто мое наблюдение)

2022-04-07 11:54 UTC, Leila-2 requested changes

2022-04-07 11:54 UTC, Leila-2 commented on src/pages/MainPage/components/Header/Header.jsx
> +          <button
А почему "Имя" это кнопка? Наверное лучше тогда раз мы сделали аватар сделать и имя и див одной кнопкой или только див) Просто это неочевидное решение, если мы повесим на значек, где должно быть имя онклик с добавлением аватарки) лучше ставить его или на сам аватар или на имя+аватар))))

2022-04-07 11:59 UTC, Leila-2 requested changes

2022-04-07 11:59 UTC, Leila-2 commented on src/pages/MainPage/components/Header/Header.jsx
> +            className="HeaderButton ExitIcon FlexGroops"
А почему вообще так много классов?) Если тебе так удобно, то ок конечно)))они на производительность не влияют, но вот запутаться в них можно) Мне напоминает BEMные макароны))))

2022-04-07 13:22 UTC, Telekaster commented on src/pages/MainPage/components/Header/Header.jsx
> +            className="HeaderButton ExitIcon FlexGroops"
Если ему так удобно, я не против

2022-04-07 13:25 UTC, Telekaster requested changes
для скрытия и появления компонентов в зависимости от разрешения экрана пожалуйста используй библиотеку [react media](https://www.npmjs.com/package/react-media)

2022-04-07 13:36 UTC, Leila-2 commented on src/pages/MainPage/components/Header/Header.jsx
> +            className="HeaderButton ExitIcon FlexGroops"
Оукей) Тогда можешь оставлять

2022-04-08 10:52 UTC, Leila-2 approved these changes

2022-04-08 10:52 UTC, merged